### Задание 1. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log.

In [28]:
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
warnings.filterwarnings('ignore')

In [37]:
def calc_logloss(y, y_pred):
    a = 1e-5
    y_pred = y_pred.copy()
    y_pred = np.clip(y_pred, a_min=a, a_max=1-a)
    err = - np.mean(y * np.log(y_pred) + (.1 - y) * np.log(1.0 - y_pred))
    return err

### Задание 2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [38]:
X = np.array([
    [   1,    1,  500,    1],
    [   1,    1,  700,    1],
    [   1,    2,  750,    2],
    [   1,    5,  600,    1],
    [   1,    3, 1450,    2],
    [   1,    0,  800,    1],
    [   1,    5, 1500,    3],
    [   1,   10, 2000,    3],
    [   1,    1,  450,    1],
    [   1,    2, 1000,    2]], dtype = np.float64)
y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

In [39]:
def standard_scale(x):
    res = (x - x.mean()) / x.std()
    return res

In [40]:
X_st = X.copy()
X_st[:, 2] = standard_scale(X[:, 2])

In [41]:
X_st

array([[ 1.        ,  1.        , -0.97958969,  1.        ],
       [ 1.        ,  1.        , -0.56713087,  1.        ],
       [ 1.        ,  2.        , -0.46401617,  2.        ],
       [ 1.        ,  5.        , -0.77336028,  1.        ],
       [ 1.        ,  3.        ,  0.97958969,  2.        ],
       [ 1.        ,  0.        , -0.36090146,  1.        ],
       [ 1.        ,  5.        ,  1.08270439,  3.        ],
       [ 1.        , 10.        ,  2.11385144,  3.        ],
       [ 1.        ,  1.        , -1.08270439,  1.        ],
       [ 1.        ,  2.        ,  0.05155735,  2.        ]])

In [42]:
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

In [45]:
def calc_logloss(y, y_pred):
    a = 1e-5
    y_pred = y_pred.copy()
    y_pred = np.clip(y_pred, a_min=a, a_max=1-a)
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    return err

In [46]:
def eval_model(X, y, iterations, eta=1e-4):
    np.random.seed(42)
    errors, weights = [], []
    W = np.random.randn(X.shape[1])
    n = X.shape[0]
    
    for i in range(iterations):
        z = np.dot(X, W)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        
        dQ = 1/n * X.T @ (y_pred - y)
        W -= eta * dQ

        errors.append(err.copy())
        weights.append(W.copy())

    return errors, weights

In [47]:
errors, weights = eval_model(X_st, y, iterations=500, eta=1e-4)
errors, weights

([1.1785958344356262,
  1.178338820611717,
  1.178081850227778,
  1.1778249232949523,
  1.1775680398244004,
  1.1773111998272563,
  1.17705440331467,
  1.1767976502977708,
  1.1765409407877048,
  1.1762842747955884,
  1.1760276523325583,
  1.1757710734097326,
  1.175514538038228,
  1.175258046229163,
  1.1750015979936494,
  1.1747451933427924,
  1.1744888322876965,
  1.174232514839463,
  1.1739762410091863,
  1.1737200108079586,
  1.1734638242468702,
  1.173207681337006,
  1.1729515820894467,
  1.1726955265152679,
  1.17243951462555,
  1.1721835464313521,
  1.1719276219437509,
  1.1716717411738031,
  1.1714159041325674,
  1.1711601108311034,
  1.1709043612804575,
  1.170648655491679,
  1.1703929934758108,
  1.1701373752438937,
  1.1698818008069622,
  1.1696262701760558,
  1.1693707833621934,
  1.1691153403764099,
  1.1688599412297176,
  1.1686045859331382,
  1.1683492744976867,
  1.1680940069343726,
  1.167838783254203,
  1.1675836034681768,
  1.167328467587298,
  1.167073375622558,
  

In [50]:
err, W = eval_model(X_st, y, iterations=100000, eta=0.1)    

In [51]:
err

[1.1785958344356262,
 0.9341629466098856,
 0.7446106563359205,
 0.62257523777082,
 0.5644242166421864,
 0.5411703584082932,
 0.5310792070157908,
 0.525929651232732,
 0.5228384190141451,
 0.5206880741298937,
 0.5190026931468144,
 0.5175654701040033,
 0.5162728409988708,
 0.5150734843756387,
 0.5139410767707725,
 0.5128615570304281,
 0.511826986373855,
 0.5108325271339763,
 0.5098749363512336,
 0.5089518084576325,
 0.5080611925972776,
 0.5072013985435906,
 0.5063708978542429,
 0.5055682731483391,
 0.5047921916696114,
 0.5040413910758923,
 0.503314671364397,
 0.5026108898673934,
 0.5019289577829532,
 0.5012678374769368,
 0.5006265401795533,
 0.5000041238930463,
 0.49939969142271234,
 0.4988123884903561,
 0.49824140191191957,
 0.49768595783171987,
 0.49714532001059303,
 0.49661878816729965,
 0.4961056963732875,
 0.4956054115010556,
 0.49511733172624417,
 0.49464088508338355,
 0.49417552807500087,
 0.49372074433358126,
 0.49327604333568986,
 0.49284095916739634,
 0.4924150493400125,
 0.4919

In [52]:
W

[array([ 0.45877546, -0.2833519 ,  0.6449505 ,  1.46641523]),
 array([ 0.42512846, -0.41299472,  0.64026463,  1.41542062]),
 array([ 0.39659734, -0.51993506,  0.63547889,  1.37272282]),
 array([ 0.3738453 , -0.59496968,  0.63374006,  1.34163043]),
 array([ 0.35603499, -0.64084928,  0.63580178,  1.32136337]),
 array([ 0.34141843, -0.66887486,  0.64021793,  1.30810252]),
 array([ 0.32880216, -0.68668744,  0.64587972,  1.29911757]),
 array([ 0.31751118, -0.6983303 ,  0.65220595,  1.2928754 ]),
 array([ 0.30714549, -0.70604056,  0.65888523,  1.28848008]),
 array([ 0.2974524 , -0.71115138,  0.6657384 ,  1.28537294]),
 array([ 0.2882646 , -0.71450514,  0.67265601,  1.28318807]),
 array([ 0.27946767, -0.71665639,  0.67956834,  1.2816777 ]),
 array([ 0.27098166, -0.71798052,  0.68642981,  1.28067032]),
 array([ 0.26274978, -0.71873631,  0.69321025,  1.28004539]),
 array([ 0.25473116, -0.71910434,  0.69988963,  1.27971729]),
 array([ 0.24689611, -0.71921149,  0.70645488,  1.27962472]),
 array([

### Задание 3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1. На вход подаётся W, который уже посчитан функцией eval_model, и X, на выходе — массив y_pred_proba.

In [53]:
def calc_pred_proba(W, X):
    y_pred = sigmoid(np.dot(W, X))
    return y_pred

### Задание 4. Создайте функцию calc_pred, возвращающую предсказанный класс. На вход подаётся W, который уже посчитан функцией eval_model, и X, на выходе — массив y_pred.

In [54]:
def calc_pred(W, X):
    p = calc_pred_proba(W, X)
    result_arr = (p > 0.45).astype(int)
    return result_arr

### Задание 5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [55]:
y_pred = sigmoid(np.dot(X, W[0]))

In [58]:
y.shape[0]

10

In [65]:
def my_accuracy_score(y, y_pred):
    return np.sum(y == y_pred) / len(y)

In [66]:
def my_confusion_matrix(y, y_pred):
    confusion_matrix = np.zeros((2, 2))
    for i in range(len(y)):
        if y_pred[i] == 1 and y[i] != 0:
            confusion_matrix[0][0] += 1
        elif y_pred[i] == 1 and y[i] !=1:
            confusion_matrix[0][1] += 1
        elif y_pred[i] == 0 and y[i] !=1:
            confusion_matrix[1][1] += 1
        else:
            confusion_matrix[1][0] += 1
    return confusion_matrix[0][0], confusion_matrix[1][1], confusion_matrix[0][1], confusion_matrix[1][0]       
            

In [67]:
def my_precision_score(y, y_pred):
    tp, tn, fp, fn = my_confusion_matrix(y, y_pred)
    return tp / (tp + fp)

In [68]:
def my_recall_score(y, y_pred):
    tp, tn, fp, fn = my_confusion_matrix(y, y_pred)
    return tp / (tp + fn)    

In [69]:
def my_f1_score(y, y_pred):
    precision = my_precision_score(y, y_pred)
    recall = my_recall_score(y, y_pred)
    return 2 * precision * recall / (precision + recall)

In [70]:
print(f'accuracy  {my_accuracy_score(y, y_pred)}')
print(f'confusion matrix {my_confusion_matrix(y, y_pred)}')
print(f'precision {my_precision_score(y, y_pred)}')
print(f'recall {my_recall_score(y, y_pred)}')
print(f'F1 {round(my_f1_score(y, y_pred), 2)}')

accuracy  0.5
confusion matrix (5.0, 0.0, 5.0, 0.0)
precision 0.5
recall 1.0
F1 0.67


### Задание 6. Могла ли модель переобучиться? Почему?

#### Модель могла переобучиться, потому что маленькая выборка и большое количество итераций.